apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: webcolor-success
spec:
  metrics:
    - name: success-rate
      interval: 30s
      count: 6
      successCondition: result > 0.9  # 90%
      failureCondition: result < 0.8  # 80%
      provider:
        prometheus:
          address: http://prometheus-server.monitoramento.svc.cluster.local
          query: | 
            scalar( 
              sum(rate(nginx_http_requests_total{app="webcolor", status=~"2..|304"}[2m])) 
              / 
              sum(rate(nginx_http_requests_total{app="webcolor"}[2m])) 
            )
